-- Migração: modo "prova completa" (simulados)
-- Rode uma vez só, depois do schema.sql + seed_questions.sql já aplicados.

-- 1. Novas colunas em questions: de qual prova a questão veio e sua ordem original.
alter table questions add column if not exists exam_source text;
alter table questions add column if not exists exam_order integer;
create index if not exists idx_questions_exam on questions(exam_source, exam_order);

-- 2. Backfill das 198 questões já existentes (seed original), marcando cada uma
--    com a prova de origem, na ordem em que foram inseridas (por id).
--    Usa row_number() em vez do valor de id diretamente, então funciona mesmo
--    que você já tenha adicionado outras questões manualmente depois do seed.
with ordered as (
  select id, row_number() over (order by id) as rn
  from questions
)
update questions q
set
  exam_source = case
    when o.rn between 1 and 50 then 'UFCG/COMPROV 2014'
    when o.rn between 51 and 150 then 'ENARE 2025/2026'
    when o.rn between 151 and 198 then 'UFPR 2023/2024'
  end,
  exam_order = case
    when o.rn between 1 and 50 then o.rn
    when o.rn between 51 and 150 then o.rn - 50
    when o.rn between 151 and 198 then o.rn - 150
  end
from ordered o
where q.id = o.id
  and o.rn <= 198
  and q.exam_source is null;

-- 3. Tabela de resultados de simulados (separada do histórico de Praticar).
create table if not exists exam_results (
  id bigint generated by default as identity primary key,
  exam_source text not null,
  total integer not null,
  correct integer not null,
  by_subject jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table exam_results enable row level security;

create policy "public read exam_results" on exam_results
  for select using (true);

create policy "public insert exam_results" on exam_results
  for insert with check (true);
