-- Sala de Estudo — Residência Grandes Animais
-- Rode isso no SQL Editor do seu projeto Supabase (uma vez só).

create table if not exists questions (
  id bigint generated by default as identity primary key,
  subject text not null,
  text text not null,
  options jsonb not null,       -- array com 5 strings, ex: ["opção A", "opção B", ...]
  correct smallint not null check (correct between 0 and 4),
  exam_source text,             -- nome da prova completa de origem (ex: "UFPR 2023/2024"), se houver
  exam_order integer,           -- posição original da questão dentro dessa prova
  created_at timestamptz not null default now()
);

create table if not exists attempts (
  id bigint generated by default as identity primary key,
  question_id bigint references questions(id) on delete set null,
  subject text not null,
  is_correct boolean not null,
  is_review boolean not null default false,
  created_at timestamptz not null default now()
);

-- Resultados de simulados (modo "prova completa"), separados do histórico de Praticar.
create table if not exists exam_results (
  id bigint generated by default as identity primary key,
  exam_source text not null,
  total integer not null,
  correct integer not null,
  by_subject jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Índices úteis para as queries de dashboard e seleção de revisão
create index if not exists idx_attempts_subject on attempts(subject);
create index if not exists idx_attempts_question on attempts(question_id);
create index if not exists idx_questions_subject on questions(subject);
create index if not exists idx_questions_exam on questions(exam_source, exam_order);

-- RLS: leitura pública das questões, leitura/escrita pública das tentativas.
-- Como é um app de uso pessoal (só vocês dois) e não guarda dado sensível,
-- deixamos aberto pela anon key. Se um dia quiser travar mais, dá pra trocar
-- "using (true)" por uma checagem de auth.uid().
alter table questions enable row level security;
alter table attempts enable row level security;
alter table exam_results enable row level security;

create policy "public read questions" on questions
  for select using (true);

create policy "public read attempts" on attempts
  for select using (true);

create policy "public insert attempts" on attempts
  for insert with check (true);

create policy "public read exam_results" on exam_results
  for select using (true);

create policy "public insert exam_results" on exam_results
  for insert with check (true);
