-- Prova completa: UFMG — Processo Seletivo de Residência Integrada em Medicina
-- Veterinária, Entrada 2025, área "Clínica Médica e Cirúrgica de Grandes Animais".
-- Fonte pública oficial: Escola de Veterinária da UFMG
-- (vet.ufmg.br/pagina/processo-seletivo-residencia/), caderno de prova e
-- gabarito pós-recurso 2025.
--
-- Do caderno original de 25 questões, 3 foram omitidas (19, 22 e 25) por
-- dependerem de imagem (endoscopia, radiografia e foto de um potro) que este
-- app ainda não suporta exibir. As 22 restantes estão completas e fiéis ao
-- texto original, com gabarito oficial.
--
-- Rode depois de sql/migration_02_exams.sql.

insert into questions (subject, text, options, correct, exam_source, exam_order) values
  ('Saúde Pública e Legislação Veterinária', 'Observe a manchete de jornal a seguir: "Cães sem coleira mordem nádega e perna de idosa em praia do litoral de SP: ''achei que ia brincar''" (G1 Santos, 10/10/2024). Sobre as medidas determinadas pelo Guia de Vigilância em Saúde no capítulo sobre a raiva, marque a alternativa CORRETA.', '["Mesmo se os animais estiverem sadios no momento do acidente, é importante que sejam mantidos em observação por 180 dias.","Deve-se avaliar se o animal estava sadio ou se apresentava sinais sugestivos de raiva. A maneira como ocorreu o acidente pode fornecer informações sobre seu estado de saúde.","A excreção de vírus rábico pela saliva, ou seja, o período em que os cães poderiam transmitir a doença, se inicia a partir do primeiro dia do período de incubação.","Animais que passam longos períodos fora do domicílio, sem controle, devem ser considerados como animais de risco, apenas se não tiverem recebido vacinas."]'::jsonb, 1, 'UFMG 2025 — Grandes Animais', 1),

  ('Saúde Pública e Legislação Veterinária', 'Em um programa de manejo ético populacional em campi universitários, deve-se pensar em estratégias para que haja uma normatização interna específica. Sobre as legislações a serem seguidas em Minas Gerais tem-se: I. A Lei Federal Nº 14.228/21 que dispõe da proibição da eliminação de cães e gatos como forma de controle populacional pelos órgãos de zoonoses, canis públicos e estabelecimentos oficiais. II. A Lei Federal nº 13.426/2017 que dispõe sobre a política de controle de natalidade de cães e gatos, por método seguro e permanente, e determina que os programas devem realizar estudo da localidade e da população, além da obrigatoriedade de desenvolver ações educativas. III. A Lei Estadual nº 21.970/2016 que dispõe sobre a proteção, a identificação e o controle populacional de cães e gatos, regulamenta e autoriza a eutanásia de animais sem tutor como medida de controle populacional, além de definir como devem ser realizadas ações de identificação e registro. É CORRETO apenas o que se afirma em:', '["I e II.","II e III.","I e III.","I, II e III."]'::jsonb, 0, 'UFMG 2025 — Grandes Animais', 2),

  ('Saúde Pública e Legislação Veterinária', 'O conhecimento e o controle das populações de escorpiões de maneira oportuna, visando à redução do número de acidentes e, consequentemente, a morbimortalidade, são atribuições do Médico Veterinário na Saúde Pública. Sobre isso, assinale a alternativa INCORRETA:', '["A ocorrência de acidentes por escorpião é de notificação compulsória no Sistema de Informação de Agravos de Notificação (Sinan), do Ministério da Saúde, e deve ser comunicada de maneira imediata ao serviço de vigilância em saúde e de vigilância e controle de animais peçonhentos, quando este existir.","Tityus serrulatus (escorpião amarelo) é o principal causador de acidentes e óbitos no Brasil.","O controle químico é a principal medida de controle recomendada pelo Ministério da Saúde, especialmente em áreas com elevada presença de baratas, seu principal alimento e atrativo em meio urbano.","Algumas espécies possuem reprodução partenogenética, ou seja, as fêmeas conseguem se reproduzir sem a presença do macho, produzindo outras fêmeas, o que contribui para sua rápida propagação."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 3),

  ('Saúde Pública e Legislação Veterinária', 'A esporotricose é a micose de implantação ou subcutânea mais prevalente e globalmente distribuída, causada por fungos do gênero Sporothrix. Sobre essa importante zoonose analise as sentenças a seguir: I. Os gatos são uma importante fonte de infecção, podendo transmitir a esporotricose por arranhadura ou mordedura. Não existem relatos de transmissão por contato com secreções de lesões cutâneo-mucosas nem respiratórias durante episódios de tosse e espirro. II. Na esporotricose de transmissão felina, a alta carga infectante geralmente determina períodos de incubação mais curtos, de uma a duas semanas. III. Recentemente foram descritos casos da doença transmitidas por procedimentos de tatuagem. É CORRETO apenas o que se afirma em:', '["I e II.","II e III.","I e III.","I, II e III."]'::jsonb, 1, 'UFMG 2025 — Grandes Animais', 4),

  ('Saúde Pública e Legislação Veterinária', 'Para atuar em casos de acumulação de animais, o médico veterinário precisa identificar os casos corretamente e saber diferenciá-los de outras situações que envolvam animais. Analise as sentenças a seguir relacionadas aos principais indicadores que devem ser observados em uma primeira visita a um possível caso de acumulação de animais: I. Moradia: desorganização do espaço, os cômodos perdem a função original. Exemplo: o sofá perdeu a função de sentar, a pia perdeu a função de lavar, e assim por diante. II. Animais: os animais são privados de bem-estar, não há conforto e as condições de higiene são precárias. III. Pessoa: a pessoa em situação de acumulação tende a negar o problema, o que pode vir acompanhado da falta de entendimento da questão, não aceitando a doação e tratamento dos animais. É CORRETO apenas o que se afirma em:', '["I e II.","II e III.","I e III.","I, II e III."]'::jsonb, 3, 'UFMG 2025 — Grandes Animais', 5),

  ('Saúde Pública e Legislação Veterinária', 'Os roedores representam cerca de 40% das espécies de mamíferos existentes e são capazes de se adaptar a diversas condições ecológicas, sobrevivendo em diferentes climas e altitudes, por meio de um grande número de adaptações morfológicas e fisiológicas, de acordo com seu estilo de vida. Sobre esses animais, analise as afirmativas a seguir: I. Das espécies de roedores consideradas sinantrópicas, três participam do ciclo de transmissão de doença, sendo a ratazana (Rattus norvegicus) a de maior relevância para a saúde pública. II. O camundongo (Mus musculus) é a menor das três espécies e as infestações geralmente são altas e de difícil controle com rodenticidas pelo hábito exacerbado de neofobia (medo do novo) da espécie. III. As trilhas com manchas de gordura deixadas pelo atrito do corpo do Rattus rattus (rato de telhado) com as estruturas verticais das construções humanas, como os cantos das paredes, das vigas etc., denotam sua presença e são decorrentes das constantes passagens do animal pelos mesmos caminhos. É CORRETO apenas o que se afirma em:', '["I e II.","II e III.","I e III.","I, II e III."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 6),

  ('Saúde Pública e Legislação Veterinária', 'O médico veterinário tem papel fundamental na vigilância e na interrupção dos ciclos de violência, promovendo um contexto de saúde única, salvando vidas humanas e reduzindo o sofrimento dos animais. Sobre a Teoria do Elo, marque a resposta INCORRETA:', '["No Brasil, o tipo mais comum de maus-tratos contra animais é a crueldade, também chamada de maus-tratos do tipo intencional.","O número de cães e gatos em casa, o nível educacional dos proprietários, as dificuldades econômicas e a presença de pessoas com deficiência são fatores associados com a ocorrência de negligência animal.","A mulher é a principal vítima no contexto da \"Teoria do Elo\", que se revela na realidade da violência doméstica. Essa é a mais comum das violências contra a mulher, deve ser detectada pelo profissional de saúde e encarada como uma questão de saúde pública.","Os animais têm sido alvo de abuso e agressão na pretensão de atingir uma pessoa. No âmbito familiar de jovens infratores foi verificado que muitos tiveram seus animais mortos por seus pais ou responsáveis, como forma de correção, repressão ou punição às atitudes dos mesmos."]'::jsonb, 0, 'UFMG 2025 — Grandes Animais', 7),

  ('Saúde Pública e Legislação Veterinária', 'Sobre a Febre Maculosa Brasileira, leia as afirmativas a seguir: I. A febre maculosa brasileira é uma doença infecciosa febril, de curso crônico e gravidade variável, cuja apresentação clínica pode variar desde as formas leves e atípicas até formas graves, com elevada taxa de letalidade. II. Embora seja o sinal clínico mais importante, o exantema pode estar ausente, o que pode dificultar e/ou retardar o diagnóstico e tratamento, determinando uma maior letalidade. III. Na Reação de Imunofluorescência indireta (RIFI), a confirmação diagnóstica ocorre quando há dois resultados reagentes, independente dos títulos de anticorpos, observado em amostras pareadas de soro. IV. A partir da suspeita de febre maculosa, a terapêutica com antibióticos deve ser iniciada imediatamente, não se devendo esperar a confirmação laboratorial do caso. Estão CORRETAS apenas as afirmativas:', '["I e II.","I e III.","II e IV.","III e IV."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 8),

  ('Clínica Médica de Grandes Animais', 'A respeito dos sinais clínicos e exame físico em equinos com abdômen agudo. I. A frequência cardíaca (FC) é um indicador da resposta fisiológica à dor, desidratação e endotoxemia, sendo útil para determinar o prognóstico em doenças do intestino delgado e intestino grosso. II. Pirexia normalmente é associada a condições como enterite anterior, colite, peritonite séptica e geralmente não requer imediata intervenção cirúrgica. III. A avaliação da cavidade bucal, como o tempo de preenchimento capilar (TPC) nos dá informação quanto ao grau de desidratação e o diagnóstico da endotoxemia. IV. A palpação transretal é um exame obrigatório e sempre deve ser realizado em pacientes com cólica, independente da idade do animal, de sua condição clínica e histórico de exames prévios. Tendo em vista as informações apresentadas, é CORRETO inferir que:', '["Apenas a alternativa I está correta.","As alternativas I, II e III estão corretas.","As alternativas I e II estão corretas.","As alternativas I, II, III, IV estão corretas."]'::jsonb, 1, 'UFMG 2025 — Grandes Animais', 9),

  ('Cirurgia de Grandes Animais', 'A respeito do manejo pré operatório do cavalo com cólica. I. O uso de antibioticoprofilaxia e agentes antiinflamatórios são recomendados. II. Os antimicrobianos recomendados são a gentamicina, que é um fármaco betalactâmico indicado para o controle das bactérias gram negativas. III. Outros fármacos indicados que são recomendados para a antibioticoprofilaxia são a enrofloxacina e cefalosporinas de quarta geração. IV. Flunixina Meglumina é um exemplo antiinflamatório não esteroidal (AINEs) recomendado para o controle da dor e endotoxemia. No que concerne o pré operatório no abdômen agudo, é CORRETO inferir que:', '["As alternativas I e II estão corretas.","As alternativas I e III estão corretas.","As alternativas I e IV estão corretas.","As alternativas I, II, III e IV estão corretas."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 10),

  ('Clínica Médica de Grandes Animais', 'A respeito dos agentes procinéticos utilizados no pós-operatório do abdômen agudo em equinos. I. Metoclopramida, Cisaprida e Mosaprida são benzamidas que podem ser utilizadas como agentes procinéticos. II. O uso da metoclopramida pode resultar em efeitos extrapiramidais como excitação, sudorese, cólicas abdominais. III. Outros exemplos de fármacos procinéticos recomendados no pós-operatório são o neostigmina e sulfato de magnésio. IV. A lidocaína é outro agente recomendado como procinético, sendo a medicação mais utilizada para a terapia do íleo paralítico. Tendo em vista as informações apresentadas, é CORRETO inferir que:', '["As alternativas I, II e IV estão corretas.","As alternativas I e II estão corretas.","Apenas a alternativa IV está correta.","As alternativas I, II, III estão corretas."]'::jsonb, 0, 'UFMG 2025 — Grandes Animais', 11),

  ('Clínica Médica de Grandes Animais', 'A tromboflebite da jugular é uma complicação comum no pós-operatório de cólica em equinos. I. Reporta-se sua ocorrência entre 7,5 a 10% de todos os cavalos submetidos a laparotomia exploratória. II. Os fatores de risco associados à tromboflebite são endotoxemia, hipoproteinemia, frequência cardíaca na admissão do paciente, tempo de preenchimento capilar (TPC) na admissão do paciente e salmonelose. III. Caso exista suspeita clínica da formação de trombose, o catéter deve ser removido imediatamente, deve-se fazer a cultura. IV. O tratamento de casos de trombose consiste basicamente na administração oral de ácido acetilsalicílico, heparina e uso de antiinflamatórios esteroidais (AIEs). Tendo em vista as informações apresentadas, é CORRETO inferir que:', '["Apenas a alternativa I está correta.","Apenas a alternativa III está correta.","As alternativas II e III estão corretas.","As alternativas I, II e III estão corretas."]'::jsonb, 3, 'UFMG 2025 — Grandes Animais', 12),

  ('Cirurgia de Grandes Animais', 'A respeito da possibilidade de exteriorização e visualização das alças intestinais durante a laparotomia exploratória em equinos (celiotomia ventral média). I. A flexura pélvica pode ser exteriorizada. II. A celiotomia ventral média permite ao cirurgião exteriorizar aproximadamente 75% do trato gastrointestinal, com exceção do estômago, duodeno e íleo distal. III. Outras porções do trato gastrointestinal que não podem ser exteriorizadas são corpo dorsal e base do ceco, cólon dorsal direito distal, cólon transverso e cólon descendente terminal. IV. O duodeno é um segmento do intestino delgado que pode ser visualizado, mas não exteriorizado. Tendo em vista as informações apresentadas, é CORRETO inferir que:', '["As alternativas I, II, III e IV estão corretas.","As alternativas I e III estão corretas.","As alternativas I, II, III estão corretas.","As alternativas I, II, IV estão corretas."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 13),

  ('Cirurgia de Grandes Animais', 'Sobre o desbridamento de ferida de equinos. I. Como exemplo de desbridamento químico temos a solução de Dakin, peróxido de hidrogênio, ácido acético e solução salina hipertônica. II. Como exemplo de desbridamento biológico temos a aplicação da larva da Lucilia sericata sobre a ferida. III. Como exemplo do desbridamento enzimático temos como exemplo substâncias como a tripsina, ureia e papaína. IV. O tratamento autolítico consiste na tripsia do tecido necrosado existente na ferida. Tendo em vista as informações apresentadas é CORRETO inferir que:', '["As alternativas I, II e III estão corretas.","Apenas a alternativa I está correta.","As alternativas III e IV estão corretas.","As alternativas I, II, III e IV estão corretas."]'::jsonb, 0, 'UFMG 2025 — Grandes Animais', 14),

  ('Cirurgia de Grandes Animais', 'A respeito da orquiectomia em equinos. I. É um dos procedimentos cirúrgicos mais realizados em equinos. II. Tem como indicação de castração unilateral ou bilateral as seguintes condições: orquites, epididimite, neoplasia testicular, hidrocele, varicocele, trauma testicular, torção do cordão espermático e hérnia inguinal. III. A castração em estação deve ser evitada em razão da dificuldade do procedimento em casos de testículo não completamente desenvolvido ou em pôneis. Deve-se evitar também a castração em estação em burros e jumentos. IV. A orquiectomia pode ser realizada com as técnicas aberta, fechada e semifechada. Tendo em vista as informações apresentadas é CORRETO inferir que:', '["Apenas a alternativa IV está correta.","Apenas as alternativas I e IV estão corretas.","Apenas as alternativas I, II e III estão corretas.","As alternativas I, II, III e IV estão corretas."]'::jsonb, 3, 'UFMG 2025 — Grandes Animais', 15),

  ('Cirurgia de Grandes Animais', 'A respeito da castração de cavalos criptorquidas. I. O testículo retido pode ser abordado cirurgicamente pela via inguinal, parainguinal, paramediana suprapúbica ou pelo flanco. II. A abordagem inguinal requer anestesia geral e decúbito dorsal e dará acesso ao testículo localizado na região inguinal ou abdominal. III. A abordagem cirúrgica pelo flanco ou paramediana possibilita apenas a criptorquidectomia do testículo localizado no abdômen. IV. Apenas a abordagem inguinal e parainguinal possibilita a remoção cirúrgica não invasiva do testículo criptorquídico. Tendo em vista as informações apresentadas é CORRETO inferir que:', '["Apenas a alternativa I está correta.","Apenas as alternativas I e II estão corretas.","Apenas as alternativas II e III estão corretas.","As alternativas I, II, III e IV estão corretas."]'::jsonb, 3, 'UFMG 2025 — Grandes Animais', 16),

  ('Clínica Médica de Grandes Animais', 'Sobre o deslocamento do abomaso à esquerda em bovinos. I. O número de casos relatados parece ter aumentado na produção de gado leiteiro internacionalmente nas últimas duas décadas, no entanto, deslocamentos à esquerda ocorrem esporadicamente em vacas de corte, assim como em bezerros e touros de corte e leite. II. O diagnóstico é baseado na ausculta e percussão simultâneas para detectar o som "ping" timpânico no lado esquerdo da vaca. III. Omentopexia da fossa paralombar esquerda pelo flanco em estação é provavelmente a abordagem mais versátil para reposicionar e estabilizar os muitos tipos de deslocamentos abomasais. IV. Antes da tentativa de reposicionar o abomaso pelas abordagens pelo flanco, é necessário a sua descompressão para facilitar a sua manipulação e posterior fixação. Tendo em vista as informações apresentadas, é CORRETO inferir que:', '["As alternativas I, II e IV estão corretas.","Apenas a alternativa I está correta.","As alternativas I e IV estão corretas.","As alternativas I, II e III estão corretas."]'::jsonb, 0, 'UFMG 2025 — Grandes Animais', 17),

  ('Cirurgia de Grandes Animais', 'Sobre cesariana em vacas. I. O objetivo da cesárea em bovinos é a remoção do bezerro quando o parto vaginal não é possível ou é improvável que produza prole viva. II. As indicações para cirurgia incluem razões maternas, como um feto relativamente grande (particularmente em novilhas imaturas ou receptoras de bezerros de transferência de embriões), dilatação cervical inadequada, conformação pélvica anormal, ruptura do tendão pré-púbico, ruptura uterina, torção uterina, inércia uterina, hidropsia do âmnio ou alantoide, e constrição vaginal congênita ou induzida por trauma. III. As indicações fetais incluem má posição fetal que são passíveis de correção pela vagina, tamanho fetal absolutamente grande, monstros fetais e fetos enfisematosos. IV. Muitos fatores são ponderados para determinar a melhor abordagem para cesárea, incluindo a experiência e preferências do cirurgião, temperamento da vaca, instalações disponíveis e se há assistência disponível. Também é útil verificar se o bezerro está vivo ou morto. Se o bezerro estiver morto, é útil determinar o estado do útero, se ele parece normal ou contraído ao redor do bezerro, ou — ainda mais importante — se o bezerro está enfisematoso. Finalmente, a vascularização do abdômen ventral da vaca também entra na tomada de decisão. Tendo em vista as informações apresentadas, é correto inferir que:', '["As alternativas I, II e IV estão corretas.","Apenas a alternativa I está correta.","As alternativas I e IV estão corretas.","As alternativas I, II e III estão corretas."]'::jsonb, 0, 'UFMG 2025 — Grandes Animais', 18),

  ('Cirurgia de Grandes Animais', 'Na traqueostomia temporária é CORRETO afirmar que:', '["O acesso é feito seccionando o músculo sternothyrohyoideus horizontalmente para isolar a traqueia.","A traqueia é incisada verticalmente utilizando no máximo 2 a 3 anéis traqueais.","A incisão é feita no meio do pescoço, afastando os músculos sternothyrohyoideus e acessando a traquéia pelo ligamento anular horizontalmente.","A abordagem é feita no terço superior, próximo a laringe, onde a traquéia está localizada mais superficialmente, assim seccionando verticalmente até 2 anéis traqueais."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 19),

  ('Clínica Médica de Grandes Animais', 'Assinale a alternativa que inclui apenas as afirmativas CORRETAS. I. Viscossuplementação refere-se à injeção de HA ou seu derivado na tentativa de devolver a elasticidade e viscosidade da membrana sinovial líquido para níveis normais ou superiores. II. Recentemente o ácido hialurônico foi classificado como um medicamento modificador de sintomas para osteoartrite versus um medicamento osteoartrítico modificador da doença. III. O uso de ácido hialurônico intravenoso para o tratamento da osteoartrite não é indicado na veterinária. IV. A associação de ácido hialurônico com corticosteróides não deve ser realizada devido ao risco de reações adversas como o aumento da claudicação. V. Todos os corticosteróides aplicados intra-articulares, atuam reduzindo a inflamação e a dor, desta forma, sempre terão efeito condroprotetor.', '["Todas as afirmativas estão corretas.","Todas as afirmativas estão incorretas.","Apenas as alternativas I, II estão corretas.","Apenas a alternativa I está correta."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 20),

  ('Clínica Médica de Grandes Animais', 'Assinale a alternativa CORRETA sobre o harpejamento em equinos:', '["O arpejo é caracterizado pela extensão involuntária exagerada do membro torácico.","A patofisiologia é incerta sendo que há duas possibilidades, uma idiopática, podendo estar associada ao trauma, com formação de fibroses na face dorsal do metatarso e outra associada à ingestão de planta tóxica.","Não há tratamento espontâneo e os cavalos afetados devem ser tratados cirurgicamente através da miectomia do tendão digital lateral.","O tratamento mais eficiente é tenectomia do tendão extensor digital comum."]'::jsonb, 1, 'UFMG 2025 — Grandes Animais', 21),

  ('Patologia Geral e Diagnóstico', 'O que é sequestro ósseo?', '["Uma inflamação óssea circunscrita associada ao trauma. É evidenciado no raio X por área cística central no osso.","É um segmento ósseo necrótico o que se separa do osso saudável sem etiologia infecciosa.","É um fragmento ósseo necrótico resultante da lise óssea de processos sépticos. Pode estar associado ao trauma e a feridas contaminadas.","Sequestro ósseo é um processo final de doença articular degenerativa que resulta na formação de ponte óssea."]'::jsonb, 2, 'UFMG 2025 — Grandes Animais', 22);
